---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 189444
custom_fields:
- name: About this plugin
  keyname: author_bio
  field_type: author_bio
  description: Like you are looking out of a watchtower. You have 3 options for scenes<br/><br/>Terrain / Grey colorscheme great for TRMNL<br> Moon / See the moon and stars in the background<br>The Original / The original idea with colors<br><br>Questions or have some great idea to add? Send me an e-mail or hit me up at Discord at @Bastronautica!<br><br> Watchtower icon created by Herra Studio @ Noun Project / All credits for the generator idea to Kevin Wang @ kwa.ng
  category: art
  email_address: trmnl@achtnegen.nl
- keyname: theme
  field_type: select
  name: What do you want to look out on?
  description: The normal terrain, or to space?
  options:
  - Terrain: terrain
  - Moon: moon
  - The Original: og
name: Watchtower
refresh_interval: 1440
